### ISSUE TITLE
Crash involving the deployer from create mod and any bucket Item

### ISSUE THREAD

**Issue by NOKIMIMO** [TeamAOF/All-of-Fabric-6#133]
By making a deployer use any kind of bucket it will crash when the action is supposed to happen. There does not need for a block or entities to be in front of the deployer (1block apart).
The save file will be locked and each time the save is loaded back it will crash.
Only i know of if your save is locked is to remove the Create mod file, load your save and then add back the Create mod.

error return code = -1
"The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7969()" because "$$0" is null"

[crash-2023-03-02_23.50.13-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/10876471/crash-2023-03-02_23.50.13-server.txt)

**Comment by jpenilla** [comment]
I ran into this earlier today. Was able to stop it from crashing with this mixin (yarn mappings):

```java
@Mixin(PlayerEntity.class)
abstract class PlayerEntityMixin {
    @Inject(method = "equipStack", at = @At("HEAD"), cancellable = true)
    void patchCreateBug(EquipmentSlot slot, ItemStack stack, CallbackInfo ci) {
        if (stack == null) {
            ci.cancel();
        }
    }
}
```

Wouldn't advise using this beyond temporarily to remove the deployers with buckets.

I think this is a Create bug (it sets held item to null for deployer's fake player) but I'm not sure since I haven't tested Create standalone.
