### ISSUE TITLE
AOF6 server crashes

### ISSUE THREAD

**Issue by dwadaw999** [TeamAOF/All-of-Fabric-6#168]
me and my friends went to the end i went inside first then the server crashes now when everyone else join they can play except when i join the server lags out

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by jpenilla** [comment]
https://github.com/TeamAOF/All-of-Fabric-6/issues/173#issuecomment-1500995922

chunky works because it does async chunk loads instead of sync chunk loads like actually going to the end will do

not sure what actually causes generation to stall out for so long (chunky at 0%/0 cps) before it starts generating at a normal speed eventually
