### ISSUE TITLE
Optional Ad Astra Quests aren't actually optional for progress

### ISSUE THREAD

**Issue by fr4mes** [TeamAOF/All-of-Fabric-6#270]
I'm not sure if im missing something but, in the quests panel, some Ad Astra quests appear as optional, but if you make the second tier rocket without doing said quests, the rocket quest doesn't count it until you beat the "optional"ones.

![imagen](https://github.com/TeamAOF/All-of-Fabric-6/assets/29447233/e9d427d7-25ef-453c-b5ff-a1c13f759287)

**Comment by jjs98** [comment]
I think this is an issue with optional quests in FTB Quests (Fabric) Mod.
Looking at the changelogs this could be fixed with version [ftb-quests-fabric-1902.4.16-build.235.jar](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric/files/4553967)
So maybe updating to the newest version of FTB Quests will fix this issue. Or remove the optional part from the quests since these Quests from Ad Astra are the only one which use this feature.
