### ISSUE TITLE
Please make BOTANY POTS work with MYSTICAL AGRICULTURE

### ISSUE THREAD

**Issue by imlostinzerogravity** [TeamAOF/All-of-Fabric-6#273]
please please please
I BEG YOU
PLEASEEEEEEEEEEEEEEEEEE

**Comment by finleyaubin** [comment]
That's kinda overpowered don't you think?

**Comment by spokrr** [comment]
not like mystical agriculture was balanced in the first place considering the numerous other autoharvester mods that exist..
the botany pots are just QOL and lag-friendliness for an inevitable broken farm anyway.

**Comment by Linguardium** [comment]
botany pots are actually not as lag friendly as you think. they tick every tick instead of every random tick, and they will iterate every slot until they find an open one. since they have a visual component, they have to update constantly. plot for plot, not using them makes more sense for lag friendliness

**Comment by Paradokku** [comment]
Mystical Agriculture works with Botany Pots, you just need to put corresponding farmland block(Tier 1/2/3/4/5) to what tier seeds you have.
