### ISSUE TITLE
Iron Chests: Restocked barrels visible in REI even though unobtainable

### ISSUE THREAD

**Issue by spokrr** [TeamAOF/All-of-Fabric-6#274]
Title says it all. 
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/69011306/b1e9fd88-b8ca-4238-bda4-667a83ae772d)
These barrels are unobtainable, even through using Chest Upgrades, and even looking through the source of the mod itself there are no recipes. This might be a WIP, in which case I believe they should be hidden from REI. Definitely just an enhancement, but a welcome one.

**Comment by jjs98** [comment]
This is an issue for the Ironchests Mod, if I were you I would close the Issue here and open one in the [other repository](https://github.com/ThatGravyBoat/Ironchests/issues) since this issue has nothing to do with this modpack.
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/47151759/14a22cce-eb4b-4a94-b583-9b9080f48694)

**Comment by Linguardium** [comment]
This modpack, however, can label those as REI hidden as it does with the unified ores and such so this issue can still apply to the pack

**Comment by jjs98** [comment]
I added a PR for IronChests to add recipes for the barrels. Maybe it will be accepted even if there are no upgrade items for the barrels yet.
