### ISSUE TITLE
[Bug] Some form of mod compatibility issue? "Charcoal" (coal) block and the EU content underflow?

### ISSUE THREAD

**Issue by MommaDragon** [TeamAOF/All-of-Fabric-6#325]
"Compressed" creates a burn time for a block item that is... so high, the Energy content is in the negative. Probably an overflow.

![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/106483611/e35bf356-bef3-4024-8324-fd1662564de6)

At least the description is unaffected. This may or may not just end up in the "wontfix" category, but. It's still good to say it's a problem.
(also, yeah, Coal blocks are considered Charcoal for compression, but that's not exactly related - recipe works fine.)

**Comment by Linguardium** [comment]
what does holding shift show?

**Comment by Linguardium** [comment]
nevermind, its an MI multiplication issue, reported here https://github.com/AztechMC/Modern-Industrialization/issues/528

**Comment by MommaDragon** [comment]
Must be ugly math.

**Comment by Linguardium** [comment]
it doesnt help that compressed adds a multiplier based on compression level (9*compression level above 1) so instead of a burn time of 104,976,000 (A) ticks (or 160,000,000 (B) if we assume every 9 blocks is worth 10 block cooktime, following vanilla's math), you get 419,904,000 (C) ...  (instead of 524,880 (A) items or 800,000 (B), you can cook 2,099,520 (C) items).

Vanilla furnace will actually truncate the value to a short, leading to 14848 cook time which is shorter than the max cooktime of 32767 (which is why you get the warnings in the console).  

Overall the compressed mod is kinda bad...

**Comment by ImAK9** [comment]
The charcoal & coal block has been disabled for now.
