### ISSUE TITLE
[Puzzles]What is it using for?

### ISSUE THREAD

**Issue by 4444Zao9** [TeamAOF/All-of-Fabric-6#358]
At KubeJS i found u added "invisible suit" and "croptopia fertilizer" but how to use them?

**Comment by Kazuhiko-Gushiken** [comment]
isnt there recipes for them? the invisible armor should also have a tooltip in game?

**Comment by 4444Zao9** [comment]
> isnt there recipes for them? the invisible armor should also have a tooltip in game?

invisible armor does have but there are no trinket slots to use them.
croptopia fertilizer doesn't have tooltip.
;(

**Comment by Kazuhiko-Gushiken** [comment]
The invisible armor was used with a cosmetic armor slot that had problems with crashing due to i think gekolib or smth. the croptopia fertilizer should have a recipe and its uses. pressing "r" over it should show its recipe and "u" over it to show its uses. it works with the new growth chamber i added

**Comment by 4444Zao9** [comment]
> The invisible armor was used with a cosmetic armor slot that had problems with crashing due to i think gekolib or smth. the croptopia fertilizer should have a recipe and its uses. pressing "r" over it should show its recipe and "u" over it to show its uses. it works with the new growth chamber i added

thx
;)
