### ISSUE TITLE
Nerf chance of Everlasting Beef

### ISSUE THREAD

**Issue by ImAK9** [TeamAOF/All-of-Fabric-6#46]

**Comment by Linguardium** [comment]
please no

**Comment by Noaaan** [comment]
In specific loot chests I have managed to find two of these things. The beef is frankly a really good artifact. It even has a lower eat time than normal food, which served to be kinda detrimental to the entire Agriculture/Food questline/rewards.
Lasts you the entire playthrough, only being replaced by more fulling/higher saturation foods much later.

**Comment by Linguardium** [comment]
it would be important to balance the loot chance then because not being able to find one in an entire playthrough of the pack (while looking) would be irritating as well since dropping from cows is disabled.

**Comment by Bellabong** [comment]
RNG is RNG. You may have found two in quick succession, but I haven't seen one in the last 70 hours. 

If the team does end up looking at everlasting beef, perhaps something to look at is the Kibe coolbox ignoring the inherent cooldown of the beef which directly counteracts its balance. (That it can't sustain you in sticky situations because of the cooldown.

**Comment by xorinzor** [comment]
I've opened a couple hundred by now and only found 1. This does indeed seem to be a case of just "lucky" RNG.
This issue should be closed.
