### ISSUE TITLE
[Suggestion] Replace Controlling with AMECS - Fabric

### ISSUE THREAD

**Issue by WraithStar** [TeamAOF/All-of-Fabric-6#79]
#63 is indeed a big issue, we definitely need a better keybind manager. There are tons of mods and functionalities in this pack that require a better handling of modifier keys so we can increase the number of the bindings we can use.

First, I tried to add AMECS but seemed not to be working. I've investigated and figured out that it conflicts with `controlling-fabric`. 
By removing that mod I was able to add more key combinations with AMECS.
We would lose Controlling's functionalities and filters, but I think it's worth it.

This is the version I tried on AOF6 1.3: https://www.curseforge.com/minecraft/mc-mods/amecs/files/3819822
No issues so far.

![immagine](https://user-images.githubusercontent.com/33436040/213190866-c8b669c5-2d2f-4fda-bbf5-77b7bcf95b41.png)

**Comment by Bellabong** [comment]
Bumping because Amecs just seems superior in every way. Started using it and no problems so far, all promised functionality works.

**Comment by parmigggiana** [comment]
[this](https://github.com/Klotzi111/amecs) amecs fork should be compatible with controlling, allowing both to coexist. I tried it and it did work. It had also solved another bug I was facing related to keybinds (#52), but for some reason that came back. It appears to be fixed with the standard amecs tho, and while some of Controlling's functionalities are lost it is worth nothing that amecs still has research with key and conflict filtering
